---
- name: "Installing python"
  hosts: "centos_python"
  become: true
  vars:
    app_name: "hello"
  tasks:
  - name: "Installing python3"
    ansible.builtin.dnf:
      name: python3
      update_cache: true

  - name: Install python deps
    ansible.builtin.dnf:
      name:
        - python3-pip
        - python3-setuptools
        - libselinux-python3
      state: latest
      update_cache: True


- name: "Pip venv"
  hosts: "centos_python"
  become: true
  vars:
    app_name: "hello"
    ansible_python_interpreter: /usr/bin/python3
    service_user: "root"
    app_user_name: "root"
    service_group: "wheel"
  tasks:
  - name: "Copy python files"
    ansible.builtin.copy:
      src: files/app
      dest: /apps/{{app_name}}
      owner: "{{ service_user }}"
      group: "{{ service_group }}"
      mode: 0644

  - name: Install virtualenv via pip
    pip:
      name: virtualenv
      executable: pip3

  - name: Install requirements
    pip:
      requirements: /apps/{{app_name}}/app/requirements.txt
      virtualenv: /apps/{{app_name}}/venv
      virtualenv_command: /usr/bin/python3 -m venv
    # become: false

  - name: Change ownership of a directory
    ansible.builtin.file:
      path: /apps
      state: directory
      recurse: yes
      owner: "{{ service_user }}"
      group: "{{ service_group }}"
    vars:
      ansible_python_interpreter: /usr/bin/python3

  - name: Allow Gunicorn binary execution
    community.general.sefcontext:
      target: "/apps/{{app_name}}/venv/bin/gunicorn"
      setype: bin_t
      state: present

  - name: Allow app directory for HTTPD read/write access
    community.general.sefcontext:
      target: "/apps/{{app_name}}(/.*)?"
      setype: httpd_sys_rw_content_t
      state: present

  - name: Apply SELinux context changes
    command: restorecon -Rv /apps/hello

  - name: Copy service file
    ansible.builtin.template:
      src: service.service.j2
      dest: /etc/systemd/system/{{app_name}}.service
      owner: "{{ service_user }}"
      group: "{{ service_group }}"
      mode: 0644

  - name: "Start service"
    service:
      name: "{{ app_name }}"
      state: started
      
