  # issue: https://github.com/ansible/ansible/issues/71634?ysclid=m8rjnnqkiz735532625
- rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2021

- name: "Installing Remi Repository"
  ansible.builtin.dnf:
    name:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
      - "https://rpms.remirepo.net/enterprise/remi-release-9.rpm"
    
- name: "Installing Remi packages"
  ansible.builtin.dnf:
    enablerepo: "php:remi-{{ php_version }}" 
    name:
      - "php"
      - "php-cli"
      - "php-fpm"
      - "php-mysqlnd"
    state: latest
    update_cache: yes

- name: "Check if we are having nginx directories"
  stat:
    path: /etc/nginx/conf.d/
  register: php_sites_available_stats

- name: "Copy php files to the separate folder"
  ansible.builtin.copy:
    src: "files/test-php/php_test/{{ item }}"
    dest: "{{ nginx_redhat_path }}"
  loop:
    - phpinfo.php
    - test-connection.php
  when: php_sites_available_stats["stat"]["exists"]

- name: "Copy php config"
  ansible.builtin.copy:
    src: files/www.conf
    dest: /etc/php-fpm.d/www.conf

- name: "Copy nginx config"
  ansible.builtin.template:
    src: nginx.centos.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  when: php_sites_available_stats.stat.exists

# - name: Delete default.conf file
#   ansible.builtin.file:
#     state: absent
#     path: /etc/nginx/conf.d/default.conf
#   when: php_sites_available_stats.stat.exists

- name: "Restart fpm"
  service:
    name: php-fpm
    state: reloaded
