---
- name: "Pip venv"
 hosts: "centos_python"
 become: false
 vars:
   app_name: "hello"
   mysql_password: "password"
   ansible_pythonr_interpreter: /usr/bin/python3
 tasks:
 - name: "Copy python files"
   ansible.builtin.copy:
     src: files/app
     dest: /apps/{{app_name}}

 - name: Install virtualenv via pip
   pip:
     name: virtualenv
     executable: pip3

 - name: Install requirements
   pip:
     requirements: /apps/{{app_name}}/app/requirements.txt
     virtualenv: /apps/{{app_name}}/venv
     virtualenv_command: /usr/bin/python3 -m venv

 - name: Copy service file
   ansible.builtin.template:
     src: service.service.j2
     dest: /etc/systemd/system/{{app_name}}.service

 - name: "Add the MySQL database"
   community.mysql.mysql_db:
     name: service_db
     state: present
     login_user: root
     login_password: "password"
     check_implicit_admin: true

 - name: "Start service"
   service:
     name: "{{ app_name }}"
     state: started