##################################################
# LEMP on Ubuntu 20.04
##################################################
---
- name: Basic group
  hosts: ubuntu:centos
  gather_facts: true
  become: true
  vars:
    test_var: test
    ansible_python_interpreter: /usr/bin/python3

  roles:
    # homework 3.10.1
    - nginx

    # homework 3.10.2
    - mysql
    - php

  tasks:

  - name: "Reload nginx"
    service:
      name: nginx
      state: reloaded