##################################################
# LEMP on Ubuntu 20.04
##################################################
---
- name: Basic group
  hosts: centos:ubuntu
  gather_facts: false
  become: true
  vars:
    test_var: test
    php_version: 7.4
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: "Install, configure, and start Apache"
      block:
        - name: "pre_tasks: Check that the /usr/bin/python2.7 exists"
          vars: 
            ansible_python_interpreter: /usr/bin/python2.7
          stat:
            path: /usr/bin/python3
          register: stat_result

        - name: "pre_tasks: Installing python3"
          vars: 
            ansible_python_interpreter: /usr/bin/python2.7
          ansible.builtin.apt:
            name: python3
            update_cache: true
          when: not stat_result.stat.exists
      ignore_errors: true

    - name: "pre_tasks: Gathering Facts"
      setup:

  roles:
    - nginx
    - mysql
    - php

  tasks:
  - name: "Reload nginx"
    service:
      name: nginx
      state: reloaded