- name: "Install mariadb and Pymysql for python related modules"
  ansible.builtin.dnf:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: latest
    update_cache: yes

- name: "Start mariadb"
  service:
    name: mariadb
    enabled: true
    state: started

- name: "Set mysql_root_password"
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock   
    name: root
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    host: localhost

# - name: "Remove remote root"
#   community.mysql.mysql_user:
#     check_implicit_admin: true
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     name: root
#     host: "{{ ansible_fqdn }}"
#     state: absent
