---
- name: Create
  hosts: 'ubuntu' 
  become: true
  gather_facts: false
  tasks:

  pre_tasks:
    - name: "Install python3"
      ansible.builtin.raw: "apt update && apt install -y python3"

    - name: "Create group vagrant"
      group:
        name: "vagrant"
        state: present

    - name: "Add the user with a primary group of sudo"
      ansible.builtin.user:
        name: vagrant
        password: "{{ 'vagrant' | password_hash('sha512')}}"
        groups: sudo, vagrant, www-data

    # - name: "Show attr"
    #   debug: 
    #     msg: "{{inventory_hostname}} {{ansible_host}} {{ansible_ssh_user | default('defaultUser')}} {{ansible_port | default('22') }} {{ansible_ssh_pass | default('defaultPassword') }} "